# Generated by Django 4.1.1 on 2022-10-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_image/')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='courses_category', to='categories.category', verbose_name='Kатегории курсов')),
            ],
        ),
    ]
