# Generated by Django 4.1.1 on 2022-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=255, verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'валюты',
                'verbose_name_plural': 'валюты',
            },
        ),
    ]
