# Generated by Django 4.1.1 on 2022-10-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
