# Generated by Django 4.1.1 on 2022-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_setting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('course', models.CharField(max_length=100, verbose_name='Курс')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
