# Generated by Django 4.1.1 on 2022-11-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
